CREATE TABLE `sys_log` (
  `id` bigint(20) NOT NULL COMMENT '主键',
  `model_code` varchar(150) NOT NULL COMMENT '模块编码',
  `model_name` varchar(150) DEFAULT NULL COMMENT '模块名称',
  `interface_code` varchar(150) DEFAULT NULL COMMENT '接口编码',
  `interface_name` varchar(200) DEFAULT NULL COMMENT '接口名称',
  `user_id` bigint(20) DEFAULT NULL COMMENT '操作用户',
  `user_name` varchar(64) DEFAULT NULL COMMENT '用户名',
  `request_url` varchar(512) DEFAULT NULL COMMENT '请求地址',
  `request_method` varchar(12) DEFAULT NULL COMMENT '请求方式',
  `input` longtext COMMENT '入参',
  `input_log_switch` tinyint(1) DEFAULT NULL COMMENT '入参记录开关',
  `log_level` varchar(12) NOT NULL COMMENT '日志级别',
  `output_log_switch` tinyint(1) DEFAULT NULL COMMENT '出差记录开关',
  `output` longtext COMMENT '出参',
  `status` tinyint(1) DEFAULT NULL COMMENT '调用结果',
  `formated_message` text COMMENT '格式化的消息',
  `http_code` int(11) DEFAULT NULL COMMENT '响应状态码',
  `business_id` bigint(20) DEFAULT NULL COMMENT '业务主键id，当前操作的业务单据id',
  `relation_business_id` bigint(20) DEFAULT NULL COMMENT '关联业务主键id，当前单据的顶级关系业务id，比如宏佳项目相关单据的project_id，用于扩展数据',
  `tenant_id` BIGINT(20) NULL DEFAULT 1 COMMENT '租户id',
  `deleted` TINYINT(1) NULL DEFAULT 0 COMMENT '删除状态： 0 未删除 1 已经删除',
  `create_by` BIGINT(20) NULL COMMENT '创建人id',
  `update_by` BIGINT(20) NULL COMMENT '修改人id',
  `create_ts` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  `update_ts` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间戳',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='系统日志';