ALTER TABLE `base_association` ADD COLUMN `sn` INT NULL DEFAULT 99999 AFTER `name`;
ALTER TABLE `base_company` ADD COLUMN `sn` INT NULL DEFAULT 99999 AFTER `name`;
ALTER TABLE `base_industry` ADD COLUMN `sn` INT NULL DEFAULT 99999 AFTER `name`;
ALTER TABLE `base_job` ADD COLUMN `sn` INT NULL DEFAULT 99999 AFTER `name`;
ALTER TABLE `base_research_domain` ADD COLUMN `sn` INT NULL DEFAULT 99999 AFTER `name`;
ALTER TABLE `base_specialism` ADD COLUMN `sn` INT NULL DEFAULT 99999 AFTER `name`;
ALTER TABLE `base_tag` ADD COLUMN `sn` INT NULL DEFAULT 99999 AFTER `name`;
