debug: true
logging:
  level:
    com.cloudok: debug
spring:
  data:
    mongodb:
#      uri: mongodb://user:pwd@ip1:port1,ip2:port2/database
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudok?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull
    username: cloudok
    password: MkPrmwQw12!
    druid:
      initial-size: 2
      min-idle: 2
      maxActive: 100
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      web-stat-filter:
        enabled: false
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet: 
        url-pattern: "/druid/*"
        enabled: false
        reset-enable: false
        login-username: root
        login-password: cloudok
  redis:
      host: 127.0.0.1
      port: 6379
      timeout: 20000
      password: 123456
      lettuce:
        pool:
          max-idle: 10
          min-idle:  10
          max-active:  100
          max-wait: -1ms
        
security: 
  token:
    secret: FxdaQYwfBmJXeIwFxZAdPGono0PW333r
    expired: 604800
    signature-secret: mESA6AB1N7iclAOM41EKhxreXXfNWP1X
    signature-expired: 300

com:
  cloudok: 
    message: 
      register:
        name: "用户注册"
        channel:
          sms:
            template:
              param: classpath*:message/template/sms/regsiter/param.flt
              title: classpath*:message/template/sms/regsiter/title.flt
              text: classpath*:message/template/sms/regsiter/text.flt
            retry:
              enable: false
            parameters:    # 渠道所需参数
              sign-name: 狮码科技    #短信签名
              template-code: SMS_41610390         #短信模板
      login:
        name: "验证码登录"
        channel:
          sms:
            template:
              param: classpath*:message/template/sms/login/param.flt
              title: classpath*:message/template/sms/login/title.flt
              text: classpath*:message/template/sms/login/text.flt
            retry:
              enable: false
            parameters:    # 渠道所需参数
              sign-name: 狮码科技   #短信签名
              template-code: SMS_41610390         #短信模板
    channel: 
      aliyun: 
        sms:
          access-key:
          access-secret:
          region-id: 
        oss:
          endpoint:
          bucket:
          base-dir:
          sign-timeout:
          access-key:
          access-secret:
        voice:
          access-key:
          access-secret:
          region-id: 
          