debug: false
logging:
  level:
    com.cloudok: info
spring:
  data:
    mongodb:
#      uri: mongodb://user:pwd@ip1:port1,ip2:port2/database
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudok?autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    druid:
      initial-size: 2
      min-idle: 2
      maxActive: 10
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      web-stat-filter:
        enabled: false
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet: 
        url-pattern: "/druid/*"
        enabled: false
        reset-enable: false
        login-username: root
        login-password: cloudok
  redis:
      host: 127.0.0.1
      port: 6379
      timeout: 20000
      password: 123456
      lettuce:
        pool:
          max-idle: 10
          min-idle:  10
          max-active:  100
          max-wait: -1ms

        
security: 
  token: 
    secret: 7olodZvQcq8DHiI165oJEPNs53ZkRPhc
    expired: 1800
    signature-secret: lfP2OQ6hlJLhgRPflsLmZv3NZuJJvGLr
    signature-expired: 300
    
    
com:
  cloudok: 
    message: 
      register:
        name: "用户注册"
        channel:
          sms:
            template:
              param: classpath*:message/template/sms/regsiter/param.flt
              title: classpath*:message/template/sms/regsiter/title.flt
              text: classpath*:message/template/sms/regsiter/text.flt
            retry:
              enable: false
            parameters:    # 渠道所需参数
              sign-name: 狮码科技    #短信签名
              template-code: SMS_41610390         #短信模板
      login:
        name: "验证码登录"
        channel:
          sms:
            template:
              param: classpath*:message/template/sms/login/param.flt
              title: classpath*:message/template/sms/login/title.flt
              text: classpath*:message/template/sms/login/text.flt
            retry:
              enable: false
            parameters:    # 渠道所需参数
              sign-name: 狮码科技   #短信签名
              template-code: SMS_41610390         #短信模板
    channel: 
      aliyun: 
        sms:
          access-key:
          access-secret:
          region-id: cn-hangzhou
        oss:
          endpoint: oss-cn-shenzhen.aliyuncs.com
          bucket: xiazhijian
          base-dir: cloudok
          sign-timeout: 1800
          access-key:
          access-secret:
        voice:
          access-key:
          access-secret:
          region-id: cn-hangzhou
          
        