debug: true
logging:
  level:
    com.cloudok: debug
spring:
  data:
    mongodb:
#      uri: mongodb://user:pwd@ip1:port1,ip2:port2/database
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-2zeua31462586x7m7125010.mysql.rds.aliyuncs.com:3306/cloudok?autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=true&serverTimezone=GMT%2B8
    username: cloudok
    password: uUl8iRI7dJsFGrDXf3Gp3jO4toY4dYbk
    druid:
      initial-size: 2
      min-idle: 2
      maxActive: 100
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      web-stat-filter:
        enabled: false
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet: 
        url-pattern: "/druid/*"
        enabled: false
        reset-enable: false
        login-username: root
        login-password: cloudok
  redis:
      host: r-2ze8hw6gfmpgd0zfvy.redis.rds.aliyuncs.com
      port: 6379
      timeout: 20000
      password: r-2ze8hw6gfmpgd0zfvy:MF2jnPt6nD7nei3Zsi3S3ygWoBZaK3rY
      lettuce:
        pool:
          max-idle: 10
          min-idle:  10
          max-active:  100
          max-wait: -1ms
        
security: 
  token:
    secret: FxdaQYwfBmJXeIwFxZAdPGono0PW333r
    expired: 7776000
    signature-secret: mESA6AB1N7iclAOM41EKhxreXXfNWP1X
    signature-expired: 300

com:
  cloudok: 
    message: 
      register:
        name: "用户注册"
        channel:
          sms:
            template:
              param: classpath*:message/template/sms/regsiter/param.flt
              title: classpath*:message/template/sms/regsiter/title.flt
              text: classpath*:message/template/sms/regsiter/text.flt
            retry:
              enable: false
            parameters:    # 渠道所需参数
              sign-name: 云可    #短信签名
              template-code: SMS_210775314         #短信模板
      login:
        name: "验证码登录"
        channel:
          sms:
            template:
              param: classpath*:message/template/sms/login/param.flt
              title: classpath*:message/template/sms/login/title.flt
              text: classpath*:message/template/sms/login/text.flt
            retry:
              enable: false
            parameters:    # 渠道所需参数
              sign-name: 云可   #短信签名
              template-code: SMS_210775314         #短信模板

    channel: 
      aliyun: 
        sms:
          access-key:
          access-secret:
          region-id: cn-beijing
        oss:
          endpoint: oss-cn-beijing.aliyuncs.com
          bucket: cloudok
          base-dir: prod
          sign-timeout: 1800
          access-key:
          access-secret:
          cdn-domain: cdn.peerer.cn
          cdn-key: peerer1201
        voice:
          access-key:
          access-secret:
          region-id: cn-beijing
          