server: 
  tomcat:
    basedir: /srv/peerer/api/temp/
  port: 8081
  servlet:
    context-path: /api
    session:
      timeout: 1800s
      
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  profiles:
    include:
      -local
      -dev
      -prod
    active: local
    
  flyway: 
    encoding: utf-8
    enabled: true
    baselineOnMigrate: true
    outOfOrder: true
    locations: classpath:db/migration/mysql
    
  jackson: 
    time-zone: GMT+8
    default-property-inclusion: non-null 
    date-format: yyyy-MM-dd HH:mm:ss
  
  cache:
    ehcache:
      config: classpath:ehcache.xml
  mvc: 
    throw-exception-if-no-handler-found: true 
    static-path-pattern : /swagger-ui.html
    
  swagger: 
    enable: true
    basePackage: com
    title: cloudok
    description: Online interface documentation
    termsOfServiceUrl: https://www.cloudok.com
    version: 1.0.0

mybatis: 
  mapper-locations:         
    - classpath*:com/cloudok/*/mapper/*.xml
    - classpath*:com/cloudok/**/mapper/*.xml
    - classpath*:mapper/auto/*/*.xml
    - classpath*:mapper/auto/**/*.xml
    - classpath*:com/cloudok/core/mapper/*.xml
  executorType: BATCH


attach: 
  business: 
    avatar: 
      name: 用户头像
      storageType: oss  #配置存储方式 存储方式需先实现存储方式接口"com.smaltech.base.attach.io.AttachIoHandle 支持 tencentCOS，aliyunOSS，localFile
      authorityInterface: attachAuthorityDefault #文件读写权限接口实现 com.smaltech.base.attach.AttachAuthorityHandle  文件读写权限接口登录校验实现 com.smaltech.base.attach.AttachAuthorityDefault用户登录即有权限上传以及下载
      fileTypes: 
        image:
          name: 图片文件
          maxSize: 50 #MB
          suffix: [jpg,jpeg,png,bmp,gif]
